### ISSUE TITLE
TranslucentTB-np does not work

### ISSUE THREAD

**Issue by SiyuChen** [Zliced13/MyScoop#9]
## Bug Report

**Package Name:** TranslucentTB-np.

### Current Behaviour
It does not really install. One can't find it in the win10 start menu. 

### Expected Behaviour
A clickable  icon should be created in the win10 start menu, then one can make the taskbar transparent by launching TranslucentTB

### Possible Solution

Instead of using TranslucentTB.bundle.msixbundle, we should use TranslucentTB.appinstaller.

 "Add-AppxPackage \"$dir\\TranslucentTB.appinstaller\" -AppInstaller"

![image](https://user-images.githubusercontent.com/22484673/213571939-00d5c091-6cb6-44ac-8aad-9389d2e2b11d.png)

![image](https://user-images.githubusercontent.com/22484673/213571074-773fda2f-b2ea-47e6-8654-bbc7c6195c70.png)

Also, see the earlier json: https://github.com/ScoopInstaller/Extras/commit/bdb12b16c66604f13fe1d18bab9d94e704417fb6

**Comment by Zliced13** [comment]
Fixed, it should work now. @SiyuChen can you test it please after running `scoop update`?

**Comment by SiyuChen** [comment]
@Zliced13 I don't have any antivirus on my laptop. After some tests, I think the problem comes from `Add-AppxPackage`.

Please see the following screenshots :

![image](https://user-images.githubusercontent.com/22484673/213811296-af72b6b2-5983-4ab1-afe5-4e0e8b4c2e84.png)
![image](https://user-images.githubusercontent.com/22484673/213811380-30365821-eff9-4939-aaa6-7d86b7ac5984.png)

![image](https://user-images.githubusercontent.com/22484673/213811838-f9e3ad62-cfd8-4d65-a43e-b11605e5b98e.png)
![image](https://user-images.githubusercontent.com/22484673/213811753-3465b8d3-8c7b-439c-9d65-4b865c65420f.png)



So, it seems that my laptop is only happy with `Add-AppxPackage .\TranslucentTB.appinstaller -AppInstaller`. 

*.msixbundle does not work and `-AppInstaller` is necessary for some reason.

**Comment by SiyuChen** [comment]
This translucenttb-np.json then works fine for me

{
    "version": "2022.1",
    "description": "Makes the Windows taskbar translucent/transparent.",
    "homepage": "https://github.com/TranslucentTB/TranslucentTB",
    "license": "GPL-3.0-only",
    "url": "https://github.com/TranslucentTB/TranslucentTB/releases/download/2022.1/TranslucentTB.appinstaller",
    "hash": "ed15932b0e4782b03c2689281e2af42e181987d836ecf06c0e1c86508295ba41",
    "pre_install": [
        "Start-Process 'powershell' -Wait -WindowStyle 'Hidden' -ArgumentList @('-C', \"Add-AppxPackage \"\"$dir\\TranslucentTB.appinstaller\"\" -AppInstaller\")",
        "Remove-Item \"$dir\\TranslucentTB.appinstaller\""
    ],
    "pre_uninstall": [
        "if (!(is_admin)) { error \"$app requires admin rights to $cmd\"; break }",
        "Remove-Item \"$env:ProgramData\\Packages\\*.TranslucentTB_*\" -Force -Recurse -ErrorAction 'SilentlyContinue'",
        "Start-Process 'powershell' -Wait -WindowStyle 'Hidden' -ArgumentList @('-C', 'Get-AppxPackage ''*.TranslucentTB'' | Remove-AppxPackage')",
        "Start-Sleep -Seconds 2"
    ],
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/TranslucentTB/TranslucentTB/releases/download/$version/TranslucentTB.appinstaller"
    }
}

**Comment by Zliced13** [comment]
@SiyuChen Try it again, it should work this time.

**Comment by SiyuChen** [comment]
Thank you very much! Confirm it works now. Is it going to be put into the nonportable bucket soon?

**Comment by Zliced13** [comment]
Hopefully yes.
